spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/shopsystem?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中

    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20

    # 配置获取连接等待超时的时间
    max-wait: 60000

    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000

    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false

    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20

    # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙 日志 log4j
    filters: stat,wall,log4j #导入了log4j
    use-global-data-source-stat: true

    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  #Redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.1.115
    # Redis服务器连接端口
    port: 6379
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制） 太小可能出现connection.PoolExcelption
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      shutdown-timeout: 100    # 关闭超时时间

  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: utf-8
    username: hynuacmteam@163.com
    password: XSHFHKJDBDEQLRYC
    test-connection: true



# mybatis
mybatis:
  type-aliases-package: com.li.shopsystem.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    com:
      li:
        shopsystem:
          mapper: DEBUG

